#!/usr/bin/env python3
"""gen_unicode_ranges.py - generate src/tokenizer/unicode_ranges.h

Builds compact [start, end] run tables for the Unicode categories the native
BPE pre-tokenizer regex needs:
  * LETTER  (\\p{L})
  * NUMBER  (\\p{N})
  * SPACE   (Unicode White_Space as used by the Rust regex crate's \\s)

The tables are generated from Python's unicodedata (same UCD the reference
tokenizer relies on) and committed so the C++ build is fully offline.
"""
from __future__ import annotations

import unicodedata
import pathlib


def runs(members: set[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in sorted(members):
        if out and cp == out[-1][1] + 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def emit(name: str, table: list[tuple[int, int]]) -> None:
    body = ",\n    ".join(f"0x{a:04XU}, 0x{b:04XU}" for a, b in table)
    print(f"// {name}: {len(table)} runs")
    print(f"constexpr uint32_t k{name}Runs[][2] = {{\n    {body}\n    }};")
    print(f"constexpr uint32_t k{name}RunCount = {len(table)};")


def main() -> None:
    letters: set[int] = set()
    numbers: set[int] = set()
    for cp in range(0x110000):
        cat = unicodedata.category(chr(cp))
        if cat.startswith("L"):
            letters.add(cp)
        elif cat.startswith("N"):
            numbers.add(cp)
    spaces = {
        0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680,
        0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006,
        0x2007, 0x2008, 0x2009, 0x200A, 0x2028, 0x2029, 0x202F,
        0x205F, 0x3000,
    }
    lines = [
        "#pragma once",
        "",
        "// Auto-generated by scripts/gen_unicode_ranges.py (do not edit).",
        "// Unicode category run tables for the native BPE pre-tokenizer.",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace glm {",
        "namespace tokenizer_detail {",
        "",
    ]
    lr, nr, sr = runs(letters), runs(numbers), runs(spaces)
    for name, table in (("Letter", lr), ("Number", nr), ("Space", sr)):
        body = ",\n    ".join(f"0x{a:04X}U, 0x{b:04X}U" for a, b in table)
        lines.append(f"// {name}: {len(table)} runs")
        lines.append(f"constexpr uint32_t k{name}Runs[][2] = {{\n    {body}\n    }};")
        lines.append(f"constexpr uint32_t k{name}RunCount = {len(table)};")
        lines.append("")
    lines.append("} // namespace tokenizer_detail")
    lines.append("} // namespace glm")
    lines.append("")
    out = pathlib.Path(__file__).resolve().parent.parent / "src" / "tokenizer" / "unicode_ranges.h"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()